cloud:
  aws:
    credentials:
      access-key: AKIA25NFHZZ5NSYOCGB5
      secret-key: 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
    region:
      static: eu-west-3
    stack:
      auto: false

application:
  bucket:
    name: carcatalogimages


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 8080